# Generated by Django 5.1.3 on 2024-11-20 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metodo_pago', '0001_initial'),
        ('ordendeservicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metodo_pago.metodo_de_pago')),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ordendeservicio.ordendeservicio')),
            ],
        ),
    ]
