# Generated by Django 5.1.3 on 2024-12-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordendeservicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendeservicio',
            name='estado',
            field=models.CharField(choices=[('Recibido', 'Recibido'), ('En Proceso', 'En Proceso'), ('Completado', 'Completado'), ('Entregado', 'Entregado')], max_length=20),
        ),
    ]
